service:
  name: alexa

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  septa-skill:
    handler: handler.handler